# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWU2KI2vXp0Wu2wmOzSsDcMGNib6IXSA
"""

!pip install pandas

import pandas as pd
b = {'city': 'Cupertino', 'phone': '408 996 1010', 'state': 'CA', 'country': 'United States', 'website': 'https://www.apple.com'  'recommendationKey' 'buy', 'gross profits': 152836000000, 'freeCashflow': 73295003648, 'targetMedianPrice': 170, 'currentPrice': 174.56, 'earningsGrowth': 0.662, 'currentRatio': 1.075}
print('Country and gross profits are' ,  b['country'], 'and',b['gross profits'])
df=pd.DataFrame(dict.items(b))
print(df)

import pandas as pd
df=pd.read_csv("rentals.csv")
df.columns
df.groupby('property_type')[['price']].mean()

import matplotlib.pyplot as plt 
price_distribution = df[df['property_type']=='price']
price_distribution2 = df[df['property_type']=='price']
plt.boxplot([price_distribution['price'], price_distribution2['price']], labels = ['price_distribution', 'price_distribution2'])
plt.show()

